import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import { listFiles, readJson, repoPath } from './repo.js';

/** The binary formats that `.gitattributes` lists. */
const BINARY_ASSET = /\.(png|jpe?g|webp|gif|mp3|wav|ogg|m4a|mp4|woff2?|ttf|otf)$/i;
/** No real content hashes to 56 leading zeros, so such a value can only be a placeholder (D14). */
const PLACEHOLDER_HASH = /^sha256:0{56}/;
const CONTENT_HASH = /^sha256:[0-9a-f]{64}$/;
/** The only place where committed binaries may live: the golden frames of D26.5. */
const GOLDEN_DIRECTORY = 'packages/test-fixtures/src/golden-frames/';
const GOLDEN_MANIFEST = `${GOLDEN_DIRECTORY}reference.golden-frames.json`;

interface ReferenceComposition {
  assets: { id: string; contentHash: string }[];
}

interface GoldenManifest {
  frames: { file: string; sha256: string }[];
}

const reference = readJson(
  'packages',
  'test-fixtures',
  'src',
  'compositions',
  'reference.json',
) as ReferenceComposition;
const hashes = reference.assets.map((asset) => asset.contentHash);
const binaries = listFiles('packages', 'test-fixtures').filter(
  (file) => BINARY_ASSET.test(file) && !/\/(dist|node_modules)\//.test(file),
);

describe('fixture assets (D14, D27.5)', () => {
  it('pins every asset with its own hash', () => {
    expect(hashes).toHaveLength(3);
    expect(new Set(hashes).size).toBe(hashes.length);
    for (const hash of hashes) expect(hash).toMatch(CONTENT_HASH);
  });

  // The placeholders of D14 were temporary; PR-06 replaced them with the hashes
  // of the generated bytes, which packages/test-fixtures/test/assets.test.ts checks.
  it('carries no placeholder hash any more', () => {
    expect(hashes.filter((hash) => PLACEHOLDER_HASH.test(hash))).toEqual([]);
  });

  it('commits no binary asset: the assets are generated, only golden frames are files', () => {
    expect(binaries.filter((file) => !file.startsWith(GOLDEN_DIRECTORY))).toEqual([]);
    for (const file of binaries) expect(file).toMatch(/\.png$/);
  });

  // D26.5: every committed golden frame is listed, with its hash, in the golden manifest.
  it('lists every golden frame with its SHA-256 in the golden manifest', () => {
    const goldens = binaries.filter((file) => file.startsWith(GOLDEN_DIRECTORY));
    if (!existsSync(repoPath(...GOLDEN_MANIFEST.split('/')))) {
      expect(goldens).toEqual([]);
      return;
    }
    const manifest = readJson(...GOLDEN_MANIFEST.split('/')) as GoldenManifest;
    expect(manifest.frames.map((frame) => `${GOLDEN_DIRECTORY}${frame.file}`).sort()).toEqual(
      goldens,
    );
    for (const frame of manifest.frames) {
      const bytes = readFileSync(repoPath(...`${GOLDEN_DIRECTORY}${frame.file}`.split('/')));
      expect(`sha256:${createHash('sha256').update(bytes).digest('hex')}`, frame.file).toBe(
        frame.sha256,
      );
    }
  });
});
