/**
 * @kadrion/editor-sdk — typed commands, patches, transactions, undo/redo.
 *
 * The one command bus that UI and AI share (`AGENTS.md`, D09, D30). A command
 * is a plain JSON value; applying one yields a new validated document and the
 * inverse command that undo needs. The package depends on `@kadrion/schema`
 * only and works without a renderer (D12). The AI tool contract of `@kadrion/ai-sdk`
 * wraps the argument schemas exported here (D31). The bus is a frozen facade
 * (D30.13); its commands come from a closed registry, and it runs transactions,
 * keeps a bounded history, and tells its listeners about every change (D38).
 */
export { applyCommand } from './apply.js';
export type { CommandResult } from './apply.js';
export { createCommandBus } from './bus.js';
export type {
  BusChange,
  BusListener,
  CommandBus,
  CommandBusOptions,
  ListenerErrorHandler,
  TransactionResult,
} from './bus.js';
export {
  addAnimationArgumentsSchema,
  addAssetArgumentsSchema,
  addKeyframeArgumentsSchema,
  addNodeArgumentsSchema,
  duplicateNodeArgumentsSchema,
  moveKeyframeArgumentsSchema,
  removeAnimationArgumentsSchema,
  removeAssetArgumentsSchema,
  removeKeyframeArgumentsSchema,
  removeNodeArgumentsSchema,
  reorderNodeArgumentsSchema,
  setImageAssetArgumentsSchema,
  setNodeColorArgumentsSchema,
  setNodeOpacityArgumentsSchema,
  setNodePositionArgumentsSchema,
  setNodeScaleArgumentsSchema,
  setNodeSizeArgumentsSchema,
  setOpacityKeyframeArgumentsSchema,
  setPositionKeyframeArgumentsSchema,
  setScaleKeyframeArgumentsSchema,
  setTextContentArgumentsSchema,
  setTextFontArgumentsSchema,
  setTextFontSizeArgumentsSchema,
} from './commands.js';
export type {
  AddAnimationArguments,
  AddAnimationArgumentsSchema,
  AddAnimationCommand,
  AddAssetArguments,
  AddAssetArgumentsSchema,
  AddAssetCommand,
  AddKeyframeArguments,
  AddKeyframeArgumentsSchema,
  AddKeyframeCommand,
  AddNodeArguments,
  AddNodeArgumentsSchema,
  AddNodeCommand,
  ArgumentSchema,
  AssetData,
  AssetType,
  ClosedObjectSchema,
  Command,
  CommandPosition,
  CommandScale,
  DuplicateNodeArguments,
  DuplicateNodeArgumentsSchema,
  DuplicateNodeCommand,
  KeyframePayloadSchema,
  MoveKeyframeArguments,
  MoveKeyframeArgumentsSchema,
  MoveKeyframeCommand,
  NodeData,
  OpenObjectSchema,
  RemoveAnimationArguments,
  RemoveAnimationArgumentsSchema,
  RemoveAnimationCommand,
  RemoveAssetArguments,
  RemoveAssetArgumentsSchema,
  RemoveAssetCommand,
  RemoveKeyframeArguments,
  RemoveKeyframeArgumentsSchema,
  RemoveKeyframeCommand,
  RemoveNodeArguments,
  RemoveNodeArgumentsSchema,
  RemoveNodeCommand,
  ReorderNodeArguments,
  ReorderNodeArgumentsSchema,
  ReorderNodeCommand,
  SetImageAssetArguments,
  SetImageAssetArgumentsSchema,
  SetImageAssetCommand,
  SetNodeColorArguments,
  SetNodeColorArgumentsSchema,
  SetNodeColorCommand,
  SetNodeOpacityArguments,
  SetNodeOpacityArgumentsSchema,
  SetNodeOpacityCommand,
  SetNodePositionArguments,
  SetNodePositionArgumentsSchema,
  SetNodePositionCommand,
  SetNodeScaleArguments,
  SetNodeScaleArgumentsSchema,
  SetNodeScaleCommand,
  SetNodeSizeArguments,
  SetNodeSizeArgumentsSchema,
  SetNodeSizeCommand,
  SetOpacityKeyframeArguments,
  SetOpacityKeyframeArgumentsSchema,
  SetOpacityKeyframeCommand,
  SetPositionKeyframeArguments,
  SetPositionKeyframeArgumentsSchema,
  SetPositionKeyframeCommand,
  SetScaleKeyframeArguments,
  SetScaleKeyframeArgumentsSchema,
  SetScaleKeyframeCommand,
  SetTextContentArguments,
  SetTextContentArgumentsSchema,
  SetTextContentCommand,
  SetTextFontArguments,
  SetTextFontArgumentsSchema,
  SetTextFontCommand,
  SetTextFontSizeArguments,
  SetTextFontSizeArgumentsSchema,
  SetTextFontSizeCommand,
} from './commands.js';
export { EditorError } from './errors.js';
export type { EditorErrorCode } from './errors.js';
export { COMMAND_TYPES, parseCommand } from './registry.js';
